version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    env_file:
      - .env
    environment:
      LLM_BASE_URL: ${DEV_OLLAMA_ADDRESS}

    # deploy: # give access to 1 gpu
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
