apiVersion: v1
kind: Service
metadata:
  name: my-service-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: my-service
